### ISSUE TITLE
Lien brand:wikadata Undefined

### ISSUE THREAD

**Issue by cayenne17** [laem/cartes#194]
Hello,

J'ai remarqué que sur les objets contenant un tag OSM `brand:wikidata`, il y a un lien.

Le lien pointe vers `https://www.wikidata.org/wiki/Undefined`
Il devrait pointer vers `https://www.wikidata.org/entity/$1` (voir : https://wiki.openstreetmap.org/wiki/Item:Q99)

**Comment by laem** [comment]
Pourrais-tu donner un exemple d'URL où cela survient ?

**Comment by laem** [comment]
Ou d'entité OSM

**Comment by Jean-BaptisteC** [comment]
https://github.com/laem/futureco/blob/master/app/voyage/useWikidata.ts

**Comment by Jean-BaptisteC** [comment]
Il semble que ces liens ne sont plus affichés sur les fiches des commerces

**Comment by cayenne17** [comment]
@Jean-BaptisteC toujours présent 
![image](https://github.com/laem/futureco/assets/47927025/84032a4a-a5ca-4b35-808d-889928d48bc9)
juste que ça pointe sur `https://www.wikidata.org/wiki/Undefined` au lieu de `https://www.wikidata.org/wiki/Q3070922`

**Comment by cayenne17** [comment]
Je vois que maintenant ça emmène vers la bonne page.

@laem @Jean-BaptisteC : Est-ce qu'il y a eu quelque chose de fait ?

Je pense que le problème peut-être fermé

**Comment by Jean-BaptisteC** [comment]
Oui le correctif a été merge, l'issue peut être clôturé

**Comment by fouss** [comment]
My bad je suis un utilisateur de gitlab mais je ne maitrise pas trop le fonctionnement des PR, désolé si j'ai pas tout bien fait au bon endroit !

**Comment by Jean-BaptisteC** [comment]
Il manquait juste le `fixes` avant le numéro de l'issue dans la PR pour fermer l'issue automatiquement une fois qu'elle est merge :)
