### ISSUE TITLE
Impossible d'accéder à une fiche d'une ville

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#251]
Sélectionner une ville sur la carte -> la fiche ne s'ouvre pas à gauche

**Comment by laem** [comment]
Ah, peut-être une évolution de OpenMapTiles qu'il faut intégrer. Je sais qu'il y avait des pb avant, peut être résolus maintenant. Merci !

**Comment by Jean-BaptisteC** [comment]
Problème corrigé en prod
