### ISSUE TITLE
Problème d'orientation des flèches de direction

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#284]
![image](https://github.com/laem/futureco/assets/87148630/a1618caf-09ad-44cc-bf88-89bdb790b2a2)

**Comment by laem** [comment]
Quel fond de carte, quel lieu ? 

Car un test rapide de mon côté me donne les bonnes flèches;

**Comment by laem** [comment]
Ah oui intéressant ! Ça ressemble à un bug de maplibre lors du diff des styles. À investiguer.
