### ISSUE TITLE
Ajout d'une barre d'échelle.

### ISSUE THREAD

**Issue by waterced** [laem/cartes#315]
Osm.org comme Gmap proposent une barre d'échelle, un tel ajout dans cartes.app serait utile :)

![image](https://github.com/laem/futureco/assets/88687679/6ce13727-5521-4b4f-8bc5-1aa73181b000)
![image](https://github.com/laem/futureco/assets/88687679/20cd72b5-448a-49e5-8fff-5511090a4e53)

**Comment by laem** [comment]
À fond. J'en suis un grand usager principalement sur les vues satellites. 
En attendant, l'outil règle pour mesurer des distances permet de s'en sortir :D

**Comment by Jean-BaptisteC** [comment]
Peu être fermé, l'échelle a été rajouté
