### ISSUE TITLE
[Tech] Comment installer cartes.app

### ISSUE THREAD

**Issue by fouss** [laem/cartes#329]
Hello, tout d'abord félicitations pour le projet c'est vraiment top !
En tant que dev web (vuejs mais c'est pas bien grave), je serais assez chaud pour contribuer tout particulièrement à cartes.app mais en lançant le projet en local tout ce qui concerne cartes redirige vers le site cartes.app du coup j'arrive pas a tester en local :(
Chaud pour un petit tips !
Merci :)

**Comment by laem** [comment]
Salut ! Merci pour ton aide :) 

Tu peux essayer de créer un fichier .env.local à la racine et y mettre "VOYAGE=oui". Normalement tu as déjà ce fichier pour y mettre la clef Map Tiler. 

Je vais inverser le comportement : voyage = oui par défaut, et pour faire tourner futur.eco (même base de code) il faudra mettre voyage=non. 

En attendant, ça devrait te débloquer. Gardons l'issue ouverte.

**Comment by fouss** [comment]
c'est tout bon merci ! :)

**Comment by laem** [comment]
C'est bon ! Il n'y a plus de question de "VOYAGE", c'est simplfié !
