### ISSUE TITLE
[Bug] réordonner les étapes d'un itinéraire sur mobile

### ISSUE THREAD

**Issue by waterced** [laem/cartes#347]
Je crois me souvenir qu'il est possible de réordonner les étapes d'un itinéraire sur la version navigateur pc (je n'y ai pas accès adj)
Je suppose que c'est le rôle des boutons entouré sur la capture d'écran ci-dessous.
Toutefois, sur mobile, je n'arrive à effectivement utiliser ces boutons. C'est tout l'encart qui slide.
![IMG_20240616_131113](https://github.com/laem/futureco/assets/88687679/894b8a7b-a4a8-49d3-b836-8a48e857bdf0)
Firefox - OnePlus Nord CE 5G -  Android 13

**Comment by laem** [comment]
Ah oui merci, c'est surement un bug introduit par les améliorations que j'ai faites à l'encart. Dégat collatéral...
