### ISSUE TITLE
Dédoublement des lignes de train

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#360]
- Ouvrir l'URL suivante https://cartes.app/?transports=oui&agence=1187#5.69/46.898/3.539
- Sélectionner la ligne C24+
- Sélectionner le bouton radio CAR
- Puis sélectionner le bouton radio TER
- Dézoomer la carte -> la ligne de train se dédouble

![image](https://github.com/laem/futureco/assets/87148630/87673716-d5d4-4a08-9b61-3c9c1d196214)

Si ça peut aider, à l'instant ou le doublon se crée dans la console du navigateur, j'ai une ligne avec `TransportMap` qui se génère

Peut être reproduit avec cette URL https://cartes.app/?transports=oui&agence=1187&routes=FR%3ALine%3A%3A2474299f-32b6-4da6-bef4-69ae2cdcae85%3A&type+de+train=ter#4.71/48.43/0.94

**Comment by laem** [comment]
Merci ! 

En fait, en prenant un peu de hauteur, cette liste des routes ne sert presque à rien. Et surtout, faire un rendu de toutes les routes, c'est très lent, et ça ralentit énormément l'affichage de la carte des transports. 

Surtout qu'on affiche des routes qui sont souvent hors champs de la carte. 

Il faut repenser ce composant, le rendre plus utile.

**Comment by Jean-BaptisteC** [comment]
Est ce que le point d'entrée de cette fonctionnalité ne pourrai pas être le nom d'un gare ?
Est en fonction on affiche toutes les routes qui partent/passent/finissent dans cette gare ?

**Comment by laem** [comment]
Oui ce serait très intéressant

**Comment by laem** [comment]
Alors normalement le bug initial de cette issue est réglé.

**Comment by laem** [comment]
J'avais notamment bossé un peu la performance du rendu des routes, donc si ça te va je te propose de la fermer et on reprendra le sujet pour améliorer le rendu de l'encart en mode carte de transports :)

**Comment by laem** [comment]
(Je ferme, mais n'hésite pas à rouvrir si ça te va pas)
