### ISSUE TITLE
Problème d'affichage de la latitude lors du partage sur mobile

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#393]
- Ouvrir l'application
- Faire un appui long sur la carte
- Appuyer sur le bouton partager
- Dans le menu de partage Android on a les infos suivantes
  - Lon 1.6166 | lat undefined + URL

Testé sur un Pixel 6 - Android 14 sur Chrome

**Comment by Jean-BaptisteC** [comment]
Surement causé par le fait qu'on gère le desktop et mobile différent pour le bouton partage
https://github.com/laem/cartes/blob/master/app/ShareButton.tsx

**Comment by laem** [comment]
Merci, c'était tout bête je crois.
