### ISSUE TITLE
Documenter l'intégration de nouvelles données GTFS

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#394]
Lors du SOTM FR 2024, il a été proposé au utilisateurs de pouvoir intégrer de nouvelles données GTFS issues de transport.data.gouv.fr.
De ma compréhension, il est nécessaire de télécharger différents repo pour mettre à jour les données et faire les tests de routage avec motis.

Une documentation serait bienvenue pour indiquer le pas à pas:
- Comment intégrer les données de transport.data.gouv.fr dans le fichier yaml
- Comment tester le routage avec Mottis

**Comment by fjg** [comment]
Il me semble que c'est ici si je ne m'abuse ➡️  https://github.com/laem/gtfs

**Comment by Jean-BaptisteC** [comment]
En ce sens, il serait peut être pertinent de faire une doc sur le repo principal qui liste les autres repos en indiquant leurs rôles dans le processus.
Et a mon sens la document GTFS doit être amélioré pour simplifier la contribution et attirer de nouveaux contributeurs

**Comment by Jean-BaptisteC** [comment]
L'intégration des données GTFS à grandement été amélioré
Il reste à mieux mettre en avant les autres repos sur le repo principal

**Comment by Jean-BaptisteC** [comment]
Un hyperlien vers le dépot contenant les fichiers gtfs à été ajouté dans contributing.md
Je ferme le ticket

**Comment by laem** [comment]
Merci ! Globalement, je pense que bientôt il y aura cartes et cartes-serveur, voir juste un seul monorepo
