### ISSUE TITLE
Autoriser la CI Vercel sur des changes fait depuis des forks

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#395]
Actuellement, la CI Vercel tombe en erreur lorsqu'un utilisateur crée une PR avec des changements issus de son fork.
Il faudrait mettre à jour ce fonctionnement pour que la CI Vercel fonctionne peut importe la source de la PR.
1. Cela permetterait de pousser des changes sans forcément avoir besoin de tout installer sur son ordinateur en local
2. Pour des petits changements de pouvoir tester rapidement et push plus rapidement sur la prod

**Comment by laem** [comment]
Salut JB ! Bien sûr, désolé de ne voir ça que maintenant

**Comment by laem** [comment]
N'hésite pas à me contacter sur @maelito:matrix.org si besoin de ce genre de choses.

**Comment by Jean-BaptisteC** [comment]
Y avait pas d'urgence particulière, je suis pas du genre à spammer pour avoir la correction rapidement
Merci de t'en être occupé
