### ISSUE TITLE
[Bug] Crash en effaçant trop rapidement un mot de la barre de recherche

### ISSUE THREAD

**Issue by waterced** [laem/cartes#413]
Pour reproduire:
 - ouvrir https://cartes.app/#14.72/48.85391/2.34365
 - taper (ou copier-coller) "libanais" (par exemple) dans la barre de recherche.
 - effacer ce texte de la barre de recherche 'rapidement' avec la touche return, et continuer à presser la touche return suffisament rapidement. Par exemple, le curseur étant à droite du mot, maintenir appuyée la touche return pour effacer le mot, et garder la touche pressée.
 - le crash survient alors.

Testé sur Win10/Firefox, Win10/Edge, ainsi que sur Android/Firefox

![image](https://github.com/laem/cartes/assets/88687679/81bfdbc3-3f11-44db-8a27-630c23dc4f9a)

**Comment by laem** [comment]
Normalement résolu par #405 :)
C'est un effet kiss cool de la refonte on dirait !

**Comment by laem** [comment]
Et merci pour la description de bug très précise qui m'a permis de le reproduire facilement.

**Comment by waterced** [comment]
Ça me semble bon !
