### ISSUE TITLE
[Bug] 'amd' au lieu de 'and' dans la lecture des tags `service:bicycle:gravel`

### ISSUE THREAD

**Issue by waterced** [laem/cartes#433]
Dans cet [encart](https://cartes.app/?allez=Basicycle%7Cn11701416503%7C2.3279%7C48.8229#18/48.8229/2.3279/20/50) les tags associés aux magasins de vélo sont lu pour être concaténés en une descritption, mais celle-ci affiche 

> Bike Fits, Bike Builds and Bike Repairs for Road, Gravel *amd* Triathlon Bikes!

au lieu de 

> Bike Fits, Bike Builds and Bike Repairs for Road, Gravel *and* Triathlon Bikes!

Je n'ai pas trouvé où c'est géré dans le code 

![image](https://github.com/user-attachments/assets/7443f755-b0af-4758-ad1e-3a725566e1c5)

**Comment by fouss** [comment]
Rien à voir avec les trad, c’est la description sur OSM qui est mal rédigée 
![IMG_5364](https://github.com/user-attachments/assets/7dd54975-391d-46b9-9ae5-16c2879153e3)

**Comment by waterced** [comment]
Ah mais oui bien sûr. Il est temps de s'arrêter pour ce soir...
