### ISSUE TITLE
Crash après s'être localisé

### ISSUE THREAD

**Issue by Chaman-veteran** [laem/cartes#440]
Pour reproduire, se localiser sur la carte, cliquer sur un objet osm (commerce, musée...) et cliquer à côté ou sur la croix.

**Comment by Jean-BaptisteC** [comment]
Peut tu réassayer le problème semble similaire à l'issue 
#437

**Comment by Chaman-veteran** [comment]
Toujours là :/ (sauf si le fix n'est pas encore en prod ?)

**Comment by laem** [comment]
Merci pour la description détaillée, normalement c'est réglé (dans 1 minute de mise en ligne) !
