### ISSUE TITLE
Ajouter plus d'espacement en hauteur sur les descriptions d'images

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#441]
Dans une description sur 2 lignes avec un hyperlien le texte de la seconde ligne est recouverte légèrement par le trait de soulignement de l'hyperlien
![Screenshot_20240722-223021](https://github.com/user-attachments/assets/3f95078b-27ff-4bd8-99d6-3deae88f6810)

**Comment by laem** [comment]
Encore merci !
