### ISSUE TITLE
Ne pas incliner la carte et garder le nord en haut après avoir sélectionné un POI

### ISSUE THREAD

**Issue by XioNoX** [laem/cartes#455]
Par exemple en allant sur https://cartes.app/?allez=Saint-Brieuc%7Cn4280767167%7C-2.7649%7C48.5073#15/48.5073/-2.7649/20/50
On est très rapidement perturbé car le nord n'est plus en haut et le point de vue est incliné. Ça demande un peu de temps pour s'habituer ou trouver le bouton pour réinitialiser la vue.

Une fois réinitialisé, ce choix n'est pas retenu, et à la sélection du POI suivant il faut refaire la même manipulation.

**Comment by laem** [comment]
CF https://github.com/laem/cartes/issues/293

**Comment by laem** [comment]
#293 est corrigé ! Déploiement en cours
