### ISSUE TITLE
Utiliser la fonctionnalité POI proches n'actualise pas le caroussel de photos wikidata

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#461]
Comment reproduire:
- Consulter ce lieu https://cartes.app/?style=base&date=2024-07-26T18h08&allez=Porte+Serpenoise%7Cw34112627%7C6.1710%7C49.1125#17.5/49.11257/6.171024/0/40
- Cliquer sur le lien Tous les Attraction proches
- Cliquer sur le POI [Ancien Château d'Eau de la Gare](https://cartes.app/?style=base&date=2024-07-26T18h08&allez=Ancien+Ch%C3%A2teau+d%27Eau+de+la+Gare%7Cw34681131%7C6.1793%7C49.1109#17.5/49.11257/6.171024/0/40) -> le carrousel n'est pas maj

**Comment by laem** [comment]
Normalement sera fixé par #464

**Comment by Jean-BaptisteC** [comment]
J'ai encore le problème :(
