### ISSUE TITLE
Coquille sur les adresses

### ISSUE THREAD

**Issue by Cyril5C** [laem/cartes#489]
Salut,
Ce n'est pas grand chose mais il y a un espace en trop avant la virgule des adresses : 
<img width="406" alt="Capture d’écran 2024-07-30 à 12 00 29" src="https://github.com/user-attachments/assets/6197b480-0ca3-433d-98c6-e15c25d49050">
Merci ! 
Cyril.

**Comment by Jean-BaptisteC** [comment]
Le problème doit se trouver ici https://github.com/laem/cartes/blob/master/components/Address.tsx

**Comment by laem** [comment]
Je corrige, mais la génération d'adresse est vraiment une science molle haha :)
