### ISSUE TITLE
Généraliser les arbres à toute la France ? 

### ISSUE THREAD

**Issue by laem** [laem/cartes#521]
D'après mes tests, la surcharge en données est légère. 

Pour bien faire les choses, il faudrait faire varier le style en fonction du type de branche, de la saison, et de l'essence. 

![image](https://github.com/user-attachments/assets/cb816c0e-2254-4d26-8da8-f5ddb48e9867)

**Comment by XioNoX** [comment]
Super !
Ainsi que les rangées d'arbres si possible (`natural=tree_row`): https://www.openstreetmap.org/way/1264562128

**Comment by laem** [comment]
C'est fait !
