### ISSUE TITLE
Visibilité des autoroutes en travaux

### ISSUE THREAD

**Issue by Chaman-veteran** [laem/cartes#536]
Salut !

Les autoroutes en travaux se voient de super loin (cf l'A69 entre Toulouse et Castres), je trouve que ça n'aide pas la lisibilité de la carte. J'ai bien buggé avant de comprendre ce que c'était, c'est une information certainement utile, mais lorsque l'on regarde très localement la situation sur la carte, est-ce qu'il serait possible d'améliorer ce point ?

**Comment by laem** [comment]
Merci !
