### ISSUE TITLE
Lien Tag "panoramax" vers une URL

### ISSUE THREAD

**Issue by cayenne17** [laem/cartes#543]
Hello,
Quand un objet est tag avec une image panoramax ([exemple](https://www.openstreetmap.org/node/11606195573)), il n'y a pas de lien vers l'image sur cartes.app ([exemple](https://cartes.app/?cat=parking-velo&allez=sans+nom%7Cn11606195573%7C-0.4497%7C46.3067)) : 
![image](https://github.com/user-attachments/assets/779bacb0-f98f-4a8a-b7ee-c30a42a43f6b)

Voici le format URL sur le [wiki item du tag panoramax sur le wiki OSM](https://wiki.openstreetmap.org/wiki/Item:Q22269) : 
`https://api.panoramax.xyz/#focus=pic&pic=$1`.

Le `$1` c'est la valeur du tag OSM à remplacer.

**Comment by laem** [comment]
Normalement c'est bon, je te laisse vérifier :)

**Comment by cayenne17** [comment]
Il n'y a pu panoramax à par l'image en haut. @laem c'est peut-être normal ?
![image](https://github.com/user-attachments/assets/261aca93-b4a0-4d71-a330-759e6c2481cb)

**Comment by laem** [comment]
Oui, les éléments qui sont intégrés à l'interface sont enlevés des tags.
