### ISSUE TITLE
Problème d'nstances panoramax

### ISSUE THREAD

**Issue by laem** [laem/cartes#569]
Sur l'adresse http://localhost:8080/?style=france&allez=La+travers%C3%A9e+de+la+biche|n12006306500|1.9370|47.9573#16/47.9573/1.937, l'image panoramax ne s'affiche pas pour l'id 60ae2b3e-17a4-410b-affb-1dbfaa2f903a

Elle a été téléchargée sur l'instance ign. Or, dans les tags OSM de ce lieu, impossible de savoir l'instance. 

Il faudrait donc faire un appel d'API. Le tag OSM ne sert donc presque à rien, si je comprends bien, car on ne sait pas l'instance sur laquelle aller la récupérer. Le tag ne sert juste qu'à faire un appel d'API de type id plutôt que de recherche lat/lon.

**Comment by cayenne17** [comment]
https://github.com/laem/cartes/blob/496364a8b35e24afc3283651a659c95f3e957d74/app/ZoneImages.tsx#L48

**Comment by laem** [comment]
Ah mais non, en fait le problème est le format du thumb ! ça marche avec le jpg

**Comment by laem** [comment]
Tant pis pour l'optimisation webp

**Comment by cayenne17** [comment]
J'ai signalé un problème : https://gitlab.com/panoramax/server/api/-/issues/182
