### ISSUE TITLE
Panoramax : les traces disparaissent lorsqu'on change de fond de carte

### ISSUE THREAD

**Issue by zorun** [laem/cartes#582]
Pour reproduire :

- ouvrir le panneau "Fond de carte"
- cocher la case "Photos de rue" : les traces Panoramax apparaissent en orange sur la carte
- changer de fond de carte : les traces disparaissent alors que la case "Photos de rue" est toujours cochée :bug: 

Pour afficher de nouveau les traces, il faut décocher et recocher la case "Photos de rue" (workaround)

**Comment by laem** [comment]
Merci :)
