### ISSUE TITLE
Cliquer sur un réseau de transport renvoie au milieu du Pacifique

### ISSUE THREAD

**Issue by roptat** [laem/cartes#593]
Bonjour,

sur Cartes, il est possible de cliquer à droite sur le bouton permettant de regarder les lignes de transport. Ça ouvre un volet à gauche qui liste entre autres les différents réseaux visibles sur la carte. Quand on clique sur l'un d'entre eux, cela permet de filtrer ce qui est affiché sur la carte, mais la carte nous transporte alors au milieu du Pacifique et dézoome au maximum.

J'ai essayé avec plusieurs réseaux de plusieurs villes de France, et ça fait la même chose à chaque fois.

Par exemple là, difficile de retrouver les lignes de Brive (indice : c'est pile sur les bords de l'écran) :)

![Copie d'écran_20240909_212555](https://github.com/user-attachments/assets/f4a1e6bb-967a-43ff-b169-47d25c828d12)

**Comment by laem** [comment]
Merci pour le retour précis ! J'ai envoyé un correctif et j'en ai profité pour clarifier le code :) 

Peux-tu re-tester ?

**Comment by roptat** [comment]
C'est bien corrigé, merci !
