### ISSUE TITLE
Erreur lors de l'affichage du calque TEC

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#594]
Activer le calque TEC -> Dans la console on a l'erreur 
```
Error: Cannot style non-existing layer "transport-routes-light-lines".
    at eQ.setPaintProperty (05f6971a-ed429d98c3b0b43f.js:2:366611)
    at e.Map.setPaintProperty (05f6971a-ed429d98c3b0b43f.js:51:208235)
    at page-772a4ed9ef6c0941.js:332:1801
```

**Comment by laem** [comment]
Je me permets de fermer, car c'est une erreur silencieuse, non ? Et surtout, que cette vue transport a tant de problèmes, il faudra y passer du temps.

**Comment by Jean-BaptisteC** [comment]
Je suis tombé par hasard dessus en regardant le ticket #593
