### ISSUE TITLE
Disparition de la carte au zoom

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/cartes#602]
J'ai ce problème depuis la mise en place de l'auto hébergement du fond de plan standard.
Parfois quand je zoom, le fond de plan disparaît totalement obligé de faire F5
Le problème semble être uniquement sur mobile
J'utilise Chrome sur un Pixel 6

**Comment by laem** [comment]
Une autre personne m'a fait le même retour. Je ne constate pas ce bug sur firefox mobile. 
À investiguer...

**Comment by Jean-BaptisteC** [comment]
Le problème semble dans Chromium même problème sur Edge desktop

Et j'ai plusieurs warnings `Too many active WebGL contexts. Oldest context will be lost.`

**Comment by laem** [comment]
OK j'ai réussi à reproduire. C'est moche ! Merci pour le signalement. 

Mais je le reproduis aussi avec les autres styles, comme celui-ci, du pur MapTiler que je n'ai pas modifié : 
cartes.app/?style=osm

Tu confirmes ?

**Comment by laem** [comment]
Je vois aussi cette erreur sur mobile.  
![image](https://github.com/user-attachments/assets/3780f46e-3a3e-47c9-9c42-1c7ac13f2d8f)

**Comment by laem** [comment]
Meilleure hypothèse : symptôme d'une fuite de mémoire.

**Comment by laem** [comment]
80 % de chances que ce soit ça : https://stackoverflow.com/questions/50684887/is-there-any-maps-per-page-limitation-in-mapbox-gl

Reste à comprendre pourquoi ça arrive : une erreur qui recréée le contexte WebGL ? Ou une mauvaise gestion de l'instanciation MapLibre par React ?

**Comment by laem** [comment]
Mmmh, une hypothèse serait que c'est la fonction isWebglSupported qui fait planter en créant les 16 contextes webgl... ce serait n'imp.

**Comment by laem** [comment]
@Jean-BaptisteC d'après mes tests, c'est corrigé. Tu peux confirmer :) ?

**Comment by laem** [comment]
J'ai vraiment merdé avec cette fonction haha

**Comment by Jean-BaptisteC** [comment]
Oui, c'est corrigé par contre la pop-up indiquant que le navigateur n'est pas supporté est visible une fraction de seconde au démarrage de la web app sur Chrome

**Comment by laem** [comment]
Oui, problème connu, compromis pour le SEO par manque de dev. Il y a une solution à trouver.
