### ISSUE TITLE
Pictos des commerces et autres POI

### ISSUE THREAD

**Issue by Cyril5C** [laem/cartes#608]
Salut,
Je crois me souvenir qu'avant il y avait des pictos pour les POI, et je crois que c'était mieux avant ;)
Vu sur Firefox / MacOS

<img width="502" alt="Capture d’écran 2024-09-18 à 16 51 08" src="https://github.com/user-attachments/assets/f3bd91ce-d159-4091-a338-8c88c2f3ef1f">

Merci !

Cyril.

**Comment by Jean-BaptisteC** [comment]
En lien avec le #516

**Comment by laem** [comment]
![image](https://github.com/user-attachments/assets/e1050fa3-0cbf-4cc6-aa03-99f7d4ee6b4a)
Je n'ai pas le problème, quelqu'un arrive à reproduire ? 

https://cartes.app/?style=france#17.41/48.874515/2.3339

**Comment by Jean-BaptisteC** [comment]
Reproduit sur Firefox Desktop en mode mobile à cet endroit https://cartes.app/?style=france#17.03/49.119313/6.173025 -> Nécessite de vider le cache CTRL+F5
Un warning est présent dans la console pour chaque image à charger `Image "chemney" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.`

**Comment by laem** [comment]
Mince je ne comprends pas... les images viennent d'un sprite.png servi par Vercel. Donc aucune chance qu'il soit indisponible. 
Ce serait un problème de code côté client. OK merci @Jean-BaptisteC j'ai reproduit en mobile seulement en effet. 
![image](https://github.com/user-attachments/assets/88a99cd6-e0c3-4e84-a92d-81ae7ebd8ed6)

**Comment by Cyril5C** [comment]
Super ça marche bien chez moi ! Top !
