### ISSUE TITLE
Les cartes ne s'affichent pas avec Firefox ESR, manque une entête CORS

### ISSUE THREAD

**Issue by bristow** [laem/cartes#623]
Je crée une issue ici au cas où des experts passent par là. Voici le problème en une seule image :  

![image](https://github.com/user-attachments/assets/bb3d67a8-82ac-4c01-9ffb-e705e7bd74d5)

J'ai décrit le problème dans ce fil du forum OSM : https://forum.openstreetmap.fr/t/probleme-affichage-cartes-app-derriere-un-firewall/27585/8

J'ai au moins 2 firewalls différents où cela ne fonctionne pas et les lycées et collèges français sont fortement impactés.

Merci :pray:

**Comment by Jean-BaptisteC** [comment]
A voir pour tester a l'avenir tous les navigateurs avec des tests automatisés en lien avec #587

**Comment by bristow** [comment]
Une belle piste là : https://forum.openstreetmap.fr/t/probleme-affichage-cartes-app-derriere-un-firewall/27585/13?u=bristow

**Comment by bristow** [comment]
Ajouter une entête CORS au serveur.cartes.app : 

`Access-Contron-Allow-Methods: GET,OPTIONS`

Cf https://forum.openstreetmap.fr/t/probleme-affichage-cartes-app-derriere-un-firewall/27585/13?u=bristow

**Comment by laem** [comment]
Merci !
